pipeline {
    agent {docker {image 'maven:3.3.3'}}
    stages {
        stage('Build') { 
            steps {
                echo "hello build" 
            }
        }
        stage('Test') { 
            steps {
                sh 'mvm --version'
            }
        }
        stage('Deploy') { 
            steps {
               echo "hello deploy"
            }
        }
    }
}