pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                echo "hello build" 
            }
        }
        stage('Test') { 
            steps {
                echo "hello Tst"
            }
        }
        stage('Deploy') { 
            steps {
               echo "hello deploy"
            }
        }
    }
}